name: ojo
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49643
title: ojo housekeeping services
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#513681'
    - '#c24be2'
    - '#050600'
    - '#d9c195'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
